"""Human and automation-oriented DataPR renderers."""

from __future__ import annotations

import json

from datapr.models import Comparison, SEVERITY_ORDER


MARKER = "<!-- datapr-report -->"


def render_json(result: Comparison) -> str:
    return json.dumps(result.to_dict(), indent=2)


def render_text(result: Comparison) -> str:
    lines = [
        f"DataPR decision: {result.decision.upper()}",
        f"Compared {result.models_base} base models with {result.models_head} head models.",
        f"Changed models: {len(result.changes)} | Findings: {len(result.findings)}",
    ]
    for change in result.changes:
        lines.append(f"\n{change.name}  {change.kind.upper()}")
        if change.downstream:
            lines.append(
                f"  downstream ({len(change.downstream)}): {', '.join(change.downstream)}"
            )
        for column in change.columns:
            detail = column.kind
            if column.before != column.after:
                detail += f" ({column.before or '-'} -> {column.after or '-'})"
            lines.append(f"  column {column.column}: {detail}")
    return "\n".join(lines)


def render_markdown(result: Comparison) -> str:
    icon = {"pass": "✅", "warn": "⚠️", "fail": "❌"}[result.decision]
    lines = [
        MARKER,
        f"## {icon} DataPR: {result.decision.upper()}",
        "",
        f"Compared **{result.models_base}** base models with **{result.models_head}** head models. "
        f"Found **{len(result.changes)}** changed models and **{len(result.findings)}** findings.",
        "",
    ]
    if result.findings:
        lines.extend(["| Severity | Model | Finding |", "|---|---|---|"])
        findings = sorted(
            result.findings,
            key=lambda item: (-SEVERITY_ORDER[item.severity], item.model, item.id),
        )
        for finding in findings:
            lines.append(
                f"| {finding.severity.upper()} | `{finding.model}` | {finding.message} |"
            )
    else:
        lines.append("No material impact was detected.")
    lines.extend(
        [
            "",
            "<details><summary>Analysis coverage</summary>",
            "",
            f"```json\n{json.dumps(result.coverage, indent=2)}\n```",
            "</details>",
            "",
            "_Generated by DataPR. Sampling and static analysis provide evidence, not proof._",
        ]
    )
    return "\n".join(lines)
