version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        data_type: bigint
      - name: customer_id
        data_type: bigint
      - name: order_total
        data_type: decimal(18,2)
      - name: created_at
        data_type: date
  - name: orders
    columns:
      - name: order_id
        data_type: bigint
      - name: customer_id
        data_type: bigint
      - name: order_total
        data_type: decimal(18,2)
      - name: created_at
        data_type: date
  - name: daily_revenue
    columns:
      - name: order_date
        data_type: date
      - name: revenue
        data_type: decimal(18,2)
